name: naver_login_sdk
description: "Flutter-Naver Login SDK. Naver is a leading web service in South Korea."
version: 0.0.9
repository: https://github.com/Lagerstroemia-Indica/flutter_naver_login_sdk/tree/main/packages/NaverLoginSDK

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_logcat: ^1.2.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: net.lagerstroemia.naver_login_sdk
        pluginClass: NaverLoginSdkPlugin
      ios:
        pluginClass: NaverLoginSdkPlugin